### ISSUE TITLE
Regenerate API only if it is needed.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio-pypi#1]
Instead of regenerating the API with every call of `generate`, using a simple checksum (for example with [checksumdir](https://pypi.org/project/checksumdir/) or a custom impl) can avoid unnecessary API generation.

**Comment by mikir** [comment]
Investigate if zserio itself could support this using timestamps checking which would work everywhere. Please note, that currently we don't know which sources are generated.

**Comment by mikir** [comment]
Another idea is to calculate checksum of sources (this will be provided by core) and to calculate checksum of generated sources. These checksums can be stored in generated directory. Please note that checksum of generated sources are necessary because user can delete or change something in generated directory.

**Comment by mikir** [comment]
This issue will be solved directly be zserio compiler: ndsev/zserio#286
